import os
import sys


SEG_CLS_NAMES = ["background", "Tree_Crown", "Tree_Trunk", 
                "Tree_Root", "Ground", "Pool", "Road", "Tree", 
                "Railings","Tree_Branch", "River"]

CLS_NAMES = ['Bird',
 'Chair',
 'Chair-Long',
 'Cloud',
 'Ground-3D',
 'Ground-cutLine',
 'Ground-grassLine',
 'Ground-Hill',
 'Ground-Horizon_High',
 'Ground-Trunk_Tail',
 'Ground-upRight',
 'Ground-Wave',
 'House',
 'Moon',
 'Mountain',
 'Mountain-Scenery',
 'Nest',
 'Nest-Birds',
 'Nest-Eggs',
 'Person',
 'Person-Face',
 'Person-Simple',
 'River',
 'River-Fish',
 'Sun',
 'Sun-Behind_Cloud',
 'Sun-On_Left',
 'Sun-On_Right',
 'Sun-With_Face',
 'Tree-Black_H',
 'Tree-Multi_2',
 'Tree-Multi_3',
 'Tree-Over_Bottom',
 'Tree-Over_Full',
 'Tree-Over_Up',
 'Tree-Simple',
 'Tree_Branch-pSwing_Left',
 'Tree_Branch-pSwing_Right',
 'Tree_Branch-Sharp',
 'Tree_Branch-Type_Close',
 'Tree_Branch-Type_Line',
 'Tree_Branch-Type_W',
 'Tree_Branch-Type_Y',
 'Tree_Crown-Apples',
 'Tree_Crown-Black_H',
 'Tree_Crown-Black_M',
 'Tree_Crown-Type_Cloud',
 'Tree_Crown-Type_Cup',
 'Tree_Crown-Type_Lines',
 'Tree_Crown-Type_mLeaf',
 'Tree_Crown-Type_sLeaf',
 'Tree_Crown-Type_X',
 'Tree_Root',
 'Tree_Root-Black_M',
 'Tree_Root-Type_Sharp',
 'Tree_Root-Type_Weak',
 'Tree_Trunk-Black',
 'Tree_Trunk-Black_M',
 'Tree_Trunk-Cut_Left',
 'Tree_Trunk-Cut_Right',
 'Tree_Trunk-Hole',
 'Tree_Trunk-Hurt_Center',
 'Tree_Trunk-Hurt_Left',
 'Tree_Trunk-Hurt_Right',
 'Tree_Trunk-Line_High',
 'Tree_Trunk-Normal']